import Phaser from "phaser";
import manifest from "./atlas.generated.json";

type Manifest = {
  sheets: Record<string, string>;
  index: Record<string, string>; // frameName -> sheet key
  origins: Record<string, number[]>;
  rotated: string[]; // frames Construct packed rotated 90°
};

const ATLAS = manifest as Manifest;
const ROTATED = new Set(ATLAS.rotated);

/**
 * Queue every Construct sprite sheet as a Phaser texture atlas (TexturePacker
 * JSON, generated by tools/extract_construct.py). Phaser handles the rotated /
 * packed frames natively, so frames are addressable as `Type:anim:index`.
 */
export function preloadSheets(load: Phaser.Loader.LoaderPlugin): void {
  for (const [sheet, imagePath] of Object.entries(ATLAS.sheets)) {
    load.atlas(sheet, imagePath, `atlas/${sheet}.json`);
  }
}

/** Which loaded atlas key holds a given frame name. */
export function sheetOf(frameName: string): string | undefined {
  return ATLAS.index[frameName];
}

/** Origin (0..1) for a frame, as authored in Construct. */
export function frameOrigin(frameName: string): { x: number; y: number } {
  const o = ATLAS.origins[frameName];
  return o ? { x: o[0], y: o[1] } : { x: 0.5, y: 0.5 };
}

export function isRotated(frameName: string): boolean {
  return ROTATED.has(frameName);
}

/**
 * Phaser 3.90's renderer ignores TexturePacker "rotated" frames, so we bake the
 * rotation out once at boot: each rotated frame becomes its own upright texture
 * keyed by the frame name. Construct packs rotated 90° clockwise, so we rotate
 * back counter-clockwise.
 */
export function normalizeRotatedFrames(textures: Phaser.Textures.TextureManager): void {
  for (const frameName of ATLAS.rotated) {
    if (textures.exists(frameName)) continue;
    const sheet = ATLAS.index[frameName];
    const tex = textures.get(sheet);
    const frame = tex.get(frameName);
    const src = tex.getSourceImage() as HTMLImageElement | HTMLCanvasElement;

    const dispW = frame.cutWidth; // un-rotated display size
    const dispH = frame.cutHeight;
    const canvas = document.createElement("canvas");
    canvas.width = dispW;
    canvas.height = dispH;
    const ctx = canvas.getContext("2d")!;
    // The packed region is dispH×dispW at (cutX,cutY); rotate it CCW into place.
    ctx.translate(0, dispH);
    ctx.rotate(-Math.PI / 2);
    ctx.drawImage(src, frame.cutX, frame.cutY, dispH, dispW, 0, 0, dispH, dispW);
    textures.addCanvas(frameName, canvas);
  }
}
